apiVersion: apps/v1
kind: Deployment
metadata:
  name: webphp-site
  labels:
    work: website-hosting
spec:
  replicas: 2
  selector:
    matchLabels:
      work: website-hosting
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: website-pod
      labels:
        work: website-hosting
    spec:
      containers:
      -  image: peace0563/webphp
         name: webphp-site
         ports:
         -  containerPort: 80
            name: webphp-site